### ISSUE TITLE
The example of deploy_workflow doesn't work.

### ISSUE THREAD

**Issue by acelan** [run-llama/llama_deploy#240]
I'm trying the example code, and only the first one runs.
How can I fix this?

```
>>> from llama_deploy import (
...     deploy_workflow,
...     WorkflowServiceConfig,
...     ControlPlaneConfig,
... )
>>> from llama_index.core.workflow import Workflow, StartEvent, StopEvent, step
>>> 
>>> # Define a sample workflow
>>> class MyWorkflow(Workflow):
...     @step()
...     async def run_step(self, ev: StartEvent) -> StopEvent:
...         arg1 = str(ev.get("arg1", ""))
...         result = arg1 + "_result"
...         return StopEvent(result=result)
... 
>>> async def main():
...             # Deploy the workflow as a service
...             await deploy_workflow(
...                 MyWorkflow(),
...                 WorkflowServiceConfig(
...                     host="127.0.0.1", port=8002, service_name="my_workflow"
...                 ),
...                 ControlPlaneConfig(),
...             )
... 
>>> if __name__ == "__main__":
...     import asyncio
...     asyncio.run(main())
... 
Traceback (most recent call last):
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<stdin>", line 3, in main
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/llama_deploy/deploy/deploy.py", line 192, in deploy_workflow
    response = await client.get(f"{control_plane_url}/queue_config")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1814, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/acelan/workspace/discord_bot/arkbot/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
```

**Comment by logan-markewich** [comment]
@acelan did you run `deploy_core()` first in another script or terminal before launching the workflow? 

You can see in the traceback it's unable to connect to the control plane

```
response = await client.get(f"{control_plane_url}/queue_config")
```

**Comment by acelan** [comment]
@logan-markewich 

You are right, thanks.
The example code should be run together.
