### ISSUE TITLE
docker image v:0.2.0 error

### ISSUE THREAD

**Issue by jdelacasa** [run-llama/llama_deploy#284]
when start docker image (v:0.2.0) and (main) get this error:

Traceback (most recent call last):
  File "/opt/entrypoint.py", line 13, in <module>
    "awssqs": AWSMessageQueueConfig(),
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 152, in __init__
    super().__init__(
  File "/opt/venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for AWSMessageQueueConfig
aws_region
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

Step to reproduce:

$ docker run -i -t llamaindex/llama-deploy:v0.2.0

Traceback (most recent call last):
  File "/opt/entrypoint.py", line 13, in <module>
    "awssqs": AWSMessageQueueConfig(),
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 152, in __init__
    super().__init__(
  File "/opt/venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for AWSMessageQueueConfig
aws_region
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by logan-markewich** [comment]
Hey @jdelacasa -- this should be fixed in the next upcoming release I think 🙏🏻 stay tuned

**Comment by jdelacasa** [comment]
great thx!
