### ISSUE TITLE
[Bug]: My inner workflow faces a timeout error

### ISSUE THREAD

**Issue by tituslhy** [run-llama/llama_deploy#320]
### Bug Description

Despite specifying a generous timeout limit for all my workflows, my inner workflow of my nested workflow always times out within 10 seconds once deployed on LlamaDeploy.
1. This error did not exist on Jupyter Notebooks
2. When I pinged the inner workflow directly using LlamaDeployClient I get no timeout error

Which means that the timeout error only happens when I ping the outer workflow which then routes to the inner workflow.

### Version

0.11.17

### Steps to Reproduce

Deployment of core
```
from llama_deploy import (
    deploy_core,
    ControlPlaneConfig,
)
from llama_deploy.message_queues.simple import (
    SimpleMessageQueueConfig
)
control_plane_config = ControlPlaneConfig()
message_queue_config = SimpleMessageQueueConfig()

if __name__ == "__main__":
    import asyncio
    
    asyncio.run(
        deploy_core(
            control_plane_config = control_plane_config,
            message_queue_config=message_queue_config,
            disable_control_plane=False,
            disable_message_queue=False,
        )
    )
```

Deployment of workflow
```
from llama_index.core.workflow import Workflow, StartEvent, StopEvent, step
import asyncio
from llama_deploy import (
    WorkflowServiceConfig,
    ControlPlaneConfig,
    deploy_workflow,
)

class InnerWorkflow(Workflow):
    @step()
    async def run_step(self, ev: StartEvent) -> StopEvent:
        result = ... #some long step here
        return StopEvent(result=str(result))


class OuterWorkflow(Workflow):
    @step()
    async def run_step(
        self, ev: StartEvent, inner: InnerWorkflow
    ) -> StopEvent:
        arg1 = ev.get("arg1")
        result = await inner.run(arg1=arg1)

        return StopEvent(result=str(result))


inner = InnerWorkflow(timeout=1200.0,verbose=True)
outer = OuterWorkflow(timeout=6000.0, verbose = True)
outer.add_workflows(inner=inner)

async def main():
    inner_task = asyncio.create_task(
        deploy_workflow(
            inner,
            WorkflowServiceConfig(
                host="127.0.0.1", port=8003, service_name="inner"
            ),
            ControlPlaneConfig(),
        )
    )

    outer_task = asyncio.create_task(
        deploy_workflow(
            outer,
            WorkflowServiceConfig(
                host="127.0.0.1", port=8002, service_name="outer"
            ),
            ControlPlaneConfig(),
        )
    )

    await asyncio.gather(inner_task, outer_task)


if name == "main":
    import asyncio
    asyncio.run(main())
```

Calling of workflow
```
from llama_deploy import AsyncLlamaDeployClient, ControlPlaneConfig
control_plane_config = ControlPlaneConfig()
client = AsyncLlamaDeployClient(control_plane_config)
session = await client.create_session()
result = await session.run(
   "outer"
   query = ...
)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/app/tlim2/anaconda3/envs/llamaindex/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 281, in handle_future_result
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/app/tlim2/anaconda3/envs/llamaindex/lib/python3.12/site-packages/llama_index/core/workflow/workflow.py", line 380, in _run_workflow
    raise WorkflowTimeoutError(msg)
llama_index.core.workflow.errors.WorkflowTimeoutError: Operation timed out after 10.0 seconds
```

**Comment by tituslhy** [comment]
@dosu Sorry I made a typo. This was how I added the inner workflow

```
inner = InnerWorkflow(timeout=1200.0,verbose=True)
outer = OuterWorkflow(timeout=6000.0, verbose = True)
outer.add_workflows(inner=inner)
```

**Comment by tituslhy** [comment]
I went to the raw file of LlamaIndex's `workflow.py` on my machine and changed the timeout settings. It works now. This means that for some reason, the nested workflow is still only calling on a default setting instead of registering my provided timeout setting.

**Comment by masci** [comment]
Hey @tituslhy thanks for reporting the issue, I'll try to reproduce and will update the issue with my findings.

**Comment by masci** [comment]
@tituslhy your code isn't working for me, the workflow seems to run but there's the error `ValueError: No consumer for 'outer' has been registered.`  buried in the logs.

So I added an `await asyncio.sleep(3)` in-between the two tasks spawning the inner and outer workflows like this:
```py
async def main():
    inner_task = asyncio.create_task(
        deploy_workflow(
            inner,
            WorkflowServiceConfig(
                host="127.0.0.1", port=8003, service_name="inner"
            ),
            ControlPlaneConfig(),
        )
    )

    await asyncio.sleep(3)

    outer_task = asyncio.create_task(
        deploy_workflow(
            outer,
            WorkflowServiceConfig(
                host="127.0.0.1", port=8002, service_name="outer"
            ),
            ControlPlaneConfig(),
        )
    )

    await asyncio.gather(inner_task, outer_task)
```
and this seems to work for me, can you try adding the sleep and let me know?

**Comment by tituslhy** [comment]
Hmm it's actually the same example as the nested workflows example here: https://docs.llamaindex.ai/en/logan-llama_deploy_docs/module_guides/workflow/deployment/

Except that the run_step in my inner workflow has a placeholder ("...") but it's a long-running step (60s). Pasting the relevant excerpt of my code here again for convenience:

```
from llama_index.core.workflow import Workflow, StartEvent, StopEvent, step

class InnerWorkflow(Workflow):
    @step()
    async def run_step(self, ev: StartEvent) -> StopEvent:
        result = ... #some long step here
        return StopEvent(result=str(result))


class OuterWorkflow(Workflow):
    @step()
    async def run_step(
        self, ev: StartEvent, inner: InnerWorkflow
    ) -> StopEvent:
        arg1 = ev.get("arg1")
        result = await inner.run(arg1=arg1)

        return StopEvent(result=str(result))


inner = InnerWorkflow(timeout=1200.0,verbose=True)
outer = OuterWorkflow(timeout=6000.0, verbose = True)
outer.add_workflows(inner=inner)
```
The problem I get is that my inner workflow always times out after 10s (which is the default) though I specified a timeout of 1200s. So I think the adding of the sleep won't fix this because I didn't face the error you faced. My Llama Deploy ran perfectly except for that inner workflow 10s timeout problem.

**Comment by masci** [comment]
@tituslhy thanks for clarifying, I was on the wrong path!

I've found the culprit, a PR with the fix is on its way.

**Comment by tituslhy** [comment]
Thanks!
