### ISSUE TITLE
race condition - pop from empty deque (orchestrators/agent.py)

### ISSUE THREAD

**Issue by styk-tv** [run-llama/llama_deploy#88]
Maybe its a mistake in example. Hard to say i'm just learning your lib.

Running this example (python 3.11.9) on latest `0.0.3.post1`
https://github.com/run-llama/llama-agents/blob/main/examples/agentic_server.py

in a loop until aborted

TRIGGER: asked for dumb question ( i guess got a dumb answer :P )
other ones (human in the loop math and secret) are processing fine

```
File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\llama_agents\control_plane\server.py", line 140, in process_message
    await self.handle_service_completion(TaskResult(**message.data))
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\llama_agents\control_plane\server.py", line 281, in handle_service_completion
    state = await self.orchestrator.add_result_to_state(task_result, task_def.state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\llama_agents\orchestrators\agent.py", line 127, in add_result_to_state
    chat_history.append(ChatMessage(role="assistant", content=str(summary)))
                                                                  ^^^^^^^
UnboundLocalError: cannot access local variable 'summary' where it is not associated with a value
ERROR:llama_agents.services.agent - Error in dumb_fact_agent processing_loop: pop from an empty deque
INFO:llama_agents.message_queues.base - Publishing message to 'control_plane' with action 'ActionTypes.COMPLETED_TASK'
INFO:llama_agents.message_queues.simple - Successfully published message 'control_plane' to consumer.
INFO:     127.0.0.1:57874 - "POST /publish HTTP/1.1" 200 OK
ERROR:llama_agents.services.agent - Error in dumb_fact_agent processing_loop: pop from an empty deque
INFO:llama_agents.message_queues.base - Publishing message to 'control_plane' with action 'ActionTypes.COMPLETED_TASK'
INFO:     127.0.0.1:57875 - "POST /publish HTTP/1.1" 200 OK
INFO:     127.0.0.1:57876 - "POST /process_message HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\routing.py", line 756, in __call__    
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\routing.py", line 297, in handle      
    await self.app(scope, receive, send)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\llama_agents\control_plane\server.py", line 140, in process_message
    await self.handle_service_completion(TaskResult(**message.data))
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\llama_agents\control_plane\server.py", line 281, in handle_service_completion
    state = await self.orchestrator.add_result_to_state(task_result, task_def.state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Piotrek\miniconda3\envs\xrvoyage\Lib\site-packages\llama_agents\orchestrators\agent.py", line 127, in add_result_to_state
    chat_history.append(ChatMessage(role="assistant", content=str(summary)))
                                                                  ^^^^^^^
UnboundLocalError: cannot access local variable 'summary' where it is not associated with a value
ERROR:llama_agents.services.agent - Error in dumb_fact_agent processing_loop: pop from an empty deque
INFO:llama_agents.message_queues.base - Publishing message to 'control_plane' with action 'ActionTypes.COMPLETED_TASK'
INFO:llama_agents.message_queues.simple - Successfully published message 'control_plane' to consumer.
INFO:     127.0.0.1:57877 - "POST /publish HTTP/1.1" 200 OK
ERROR:llama_agents.services.agent - Error in dumb_fact_agent processing_loop: pop from an empty deque
INFO:llama_agents.message_queues.base - Publishing message to 'control_plane' with action 'ActionTypes.COMPLETED_TASK'
INFO:     127.0.0.1:57878 - "POST /publish HTTP/1.1" 200 OK
INFO:     127.0.0.1:57879 - "POST /process_message HTTP/1.1" 500 Internal Server Error
```

EDIT:

I also discovered error about tool choice (one of the agents has list of empty tools), if this is to cause error perhaps it shouldn't be accepted into the queue in the first place?

This is preceeding the above error (however no refusal to accept, all calls are 200's)

```
INFO:llama_agents.message_queues.base - Publishing message to 'dumb_fact_agent' with action 'ActionTypes.NEW_TASK'
INFO:     127.0.0.1:61039 - "POST /publish HTTP/1.1" 200 OK
INFO:     127.0.0.1:61036 - "POST /tasks HTTP/1.1" 200 OK
INFO:     127.0.0.1:61040 - "POST /process_message HTTP/1.1" 200 OK
INFO:llama_agents.message_queues.simple - Successfully published message 'dumb_fact_agent' to consumer.
ERROR:llama_agents.services.agent - Error in dumb_fact_agent processing_loop: Error code: 400 - {'error': {'message': "Invalid value for 'tool_choice': 'tool_choice' is only allowed when 'tools' are specified.", 'type': 'invalid_request_error', 'param': 'tool_choice', 'code': None}}
INFO:llama_agents.message_queues.base - Publishing message to 'control_plane' with action 'ActionTypes.COMPLETED_TASK'
INFO:     127.0.0.1:61042 - "POST /publish HTTP/1.1" 200 OK
ERROR:llama_agents.services.agent - Error in dumb_fact_agent processing_loop: pop from an empty deque
INFO:llama_agents.message_queues.base - Publishing message to 'control_plane' with action 'ActionTypes.COMPLETED_TASK'
```

**Comment by logan-markewich** [comment]
interesting

It's hard to know whether an error can be resolved by alternative prompting or if it's an actual unresolvable issue. The agent services have an attribute to raise on error
https://github.com/run-llama/llama-agents/blob/c355bf9c0c4ca64a55eb733e74e82013c233b7b8/llama_agents/services/agent.py#L66

Which gets used here
https://github.com/run-llama/llama-agents/blob/c355bf9c0c4ca64a55eb733e74e82013c233b7b8/llama_agents/services/agent.py#L224

This specific error here needs to be fixed in `llama-index-core` I think

**Comment by styk-tv** [comment]
how to repro: there are 3 services in that example

1. HumanService
and 2x AgentService

Human and with adding numbers and Secret are working fine.  Last AgentService (without the tool: `worker2 = FunctionCallingAgentWorker.from_tools([], llm=OpenAI())` is causing issues.

I am able to repro with command "tell me a dumb fact" since the description is "Useful for getting random dumb facts." At that time race condition is triggered. (sent from CLI tool)

I hope this helps @logan-markewich - anything you want me to retest let me know. I am working on integration of llama-agent with my service.

**Comment by logan-markewich** [comment]
@styk-tv thanks! Yea the issue with no tools + tool choice just needs to be resolved in `llama-index-core` -- should be easy enough to tackle today
