### ISSUE TITLE
TypeError: ReActAgentWorker.__init__() got an unexpected keyword argument 'error_on_no_tool_call'

### ISSUE THREAD

**Issue by teds-lin** [run-llama/llama_deploy#93]
Is Google Gemini supported?

I try execute the code as follows:
```python
import dotenv

dotenv.load_dotenv()

from llama_agents import (
    AgentService,
    AgentOrchestrator,
    ControlPlaneServer,
    SimpleMessageQueue,
)

from llama_index.core.agent import ReActAgent
from llama_index.core.tools import FunctionTool
from llama_index.llms.gemini import Gemini
from llama_index.embeddings.gemini import GeminiEmbedding
from llama_index.core import Settings
import logging

Settings.embed_model = GeminiEmbedding()


# create an agent
def get_the_secret_fact() -> str:
    """Returns the secret fact."""
    return "The secret fact is: A baby llama is called a 'Cria'."


tool = FunctionTool.from_defaults(fn=get_the_secret_fact)

agent1 = ReActAgent.from_tools([tool], llm=Gemini())
agent2 = ReActAgent.from_tools([], llm=Gemini())

# create our multi-agent framework components
message_queue = SimpleMessageQueue(port=8000)
control_plane = ControlPlaneServer(
    message_queue=message_queue,
    orchestrator=AgentOrchestrator(llm=Gemini()),
    port=8001,
)
agent_server_1 = AgentService(
    agent=agent1,
    message_queue=message_queue,
    description="Useful for getting the secret fact.",
    service_name="secret_fact_agent",
    port=8002,
)
agent_server_2 = AgentService(
    agent=agent2,
    message_queue=message_queue,
    description="Useful for getting random dumb facts.",
    service_name="dumb_fact_agent",
    port=8003,
)

from llama_agents import LocalLauncher

# launch it
launcher = LocalLauncher(
    [agent_server_2],
    control_plane,
    message_queue,
)

result = launcher.launch_single("What is the secret fact?")

print(f"Result: {result}")
```

This code will have an error
```log
result = launcher.launch_single("What is the secret fact?")
```

Log message:
```log

INFO:llama_agents.message_queues.simple - Consumer AgentService-f6705c0b-f20e-460a-a018-e908ff7589b8: dumb_fact_agent has been registered.
INFO:llama_agents.message_queues.simple - Consumer a4e71d0f-6575-44c2-962d-78f0f308fa13: human has been registered.
INFO:llama_agents.message_queues.simple - Consumer ControlPlaneServer-4e122b27-2817-4f87-b2d5-607d5553c143: control_plane has been registered.
INFO:llama_agents.services.agent - dumb_fact_agent launch_local
INFO:llama_agents.message_queues.base - Publishing message to 'control_plane' with action 'ActionTypes.NEW_TASK'
INFO:llama_agents.message_queues.simple - Launching message queue locally
Traceback (most recent call last):
  File "D:\workspace\test\test2.py", line 64, in <module>
    result = launcher.launch_single("What is the secret fact?")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\launchers\local.py", line 74, in launch_single
    return asyncio.run(self.alaunch_single(initial_task))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\launchers\local.py", line 129, in alaunch_single
    raise mq_task.exception()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\message_queues\simple.py", line 279, in processing_loop    
    await self._publish_to_consumer(message)
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\message_queues\simple.py", line 200, in _publish_to_consumer
    await consumer.process_message(message, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\message_consumers\base.py", line 33, in process_message    
    return await self._process_message(message, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\message_consumers\callable.py", line 13, in _process_message
    await self.handler(message, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\control_plane\server.py", line 138, in process_message     
    await self.create_task(TaskDefinition(**message.data))
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\control_plane\server.py", line 235, in create_task
    task_def = await self.send_task_to_service(task_def)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\control_plane\server.py", line 263, in send_task_to_service    next_messages, task_state = await self.orchestrator.get_next_messages(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_agents\orchestrators\agent.py", line 53, in get_next_messages     
    response = await self.llm.apredict_and_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\test\Lib\site-packages\llama_index\core\llms\llm.py", line 650, in apredict_and_call
    worker = ReActAgentWorker(
             ^^^^^^^^^^^^^^^^^
TypeError: ReActAgentWorker.__init__() got an unexpected keyword argument 'error_on_no_tool_call'
```

**Comment by logan-markewich** [comment]
@teds-lin what version of llama-index-core do you have? Try `pip install -U llama-index-core`

**Comment by logan-markewich** [comment]
(It definitely should be supported)

**Comment by logan-markewich** [comment]
Actually, I'm a little confused how that arg got passed there. Might need a fix in `llama-index-core`
